name: cosmwasm starter CICD

on:
  push:
    branches: [ main,dev ]

jobs:

  build:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Run local build
      run: |
        npm install --global yarn
        npm install -g @subql/cli
        yarn install
        subql codegen
        CI=false subql build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: ap-southeast-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Tag, push  image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: cosmwasm-starter
        IMAGE_TAG: ${{ github.ref_name }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - name: Redeploy on aws
      env:
        SUFFIX: ${{ fromJson('["-prod -n webapp", "-dev"]')[github.ref_name == 'dev'] }}
      run: |
        aws eks update-kubeconfig --region  ap-southeast-1 --name ${{ secrets.EKS_CLUSTER }}
